[package]
name = "berrysoft-data-parquet-jni"
version = "0.1.0"
edition = "2021"

[lib]
path = "src-rust/lib.rs"
crate-type = ["cdylib"]

[dependencies]
jni = "0.21"
arrow-array = "42"
arrow-buffer = "42"
arrow-data = "42"
arrow-schema = "42"
parquet = "42"
thiserror = "1"

[profile.release]
lto = true
codegen-units = 1
