[package]
name = "berrysoft-data-parquet-jni"
version = "0.1.0"
edition = "2021"

[lib]
path = "src-rust/lib.rs"
crate-type = ["cdylib"]

[dependencies]
jni = "0.21"
arrow-array = "45"
arrow-buffer = "46"
arrow-data = "45"
arrow-schema = "45"
parquet = "45"
thiserror = "1"

[profile.release]
lto = true
codegen-units = 1
